# Generated by Django 3.2.6 on 2024-05-02 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('electricity_start_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('occupants', models.PositiveIntegerField()),
                ('security_deposit', models.PositiveIntegerField()),
                ('rent_fee', models.PositiveIntegerField()),
                ('electricity_fee', models.PositiveIntegerField()),
                ('water_fee', models.PositiveIntegerField()),
                ('internet_fee', models.PositiveIntegerField()),
                ('charging_fee', models.PositiveIntegerField()),
                ('other_fee', models.PositiveIntegerField()),
                ('other_fee_desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField()),
                ('electricity_start', models.DecimalField(decimal_places=2, max_digits=10)),
                ('electricity_end', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unpaid_amount', models.PositiveIntegerField(default=0)),
                ('total_amount', models.PositiveIntegerField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, verbose_name='Room number')),
                ('max_occupancy', models.PositiveSmallIntegerField(default=3, verbose_name='Max occupancy')),
                ('electric_device_id', models.CharField(max_length=50, verbose_name='Electric Device ID')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('electricity_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.room')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('cccd', models.TextField(max_length=12, verbose_name='CCCD')),
                ('cccd_image_front', models.ImageField(upload_to='', verbose_name='CCCD Front')),
                ('cccd_image_back', models.ImageField(upload_to='', verbose_name='CCCD Back')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.customer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.room'),
        ),
    ]
