# Generated by Django 3.2.6 on 2024-05-04 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20240503_0540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricity',
            options={'verbose_name': 'Electricity', 'verbose_name_plural': 'Electricities'},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='customer',
        ),
        migrations.CreateModel(
            name='ContractCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.contract')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.customer')),
            ],
        ),
    ]
