# Generated by Django 3.2.6 on 2024-05-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20240504_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='customers',
            field=models.ManyToManyField(through='department.ContractCustomer', to='department.Customer'),
        ),
    ]
