# Generated by Django 3.2.6 on 2024-05-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_contract_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cleaning_fee',
            field=models.PositiveIntegerField(default=100000),
            preserve_default=False,
        ),
    ]
