# Generated by Django 3.2.6 on 2024-05-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0005_contract_cleaning_fee"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='room',
        #     name='door_key',
        #     field=models.PositiveSmallIntegerField(default=123456, max_length=6, verbose_name='Door key'),
        #     preserve_default=False,
        # ),
    ]
