# Generated by Django 3.2.6 on 2024-05-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_room_door_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='charging_fee',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='cleaning_fee',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='electricity_fee',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='internet_fee',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='other_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='other_fee_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rent_fee',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='water_fee',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
