# Generated by Django 3.2.6 on 2024-05-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_auto_20240523_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cccd',
            field=models.TextField(blank=True, null=True, verbose_name='CCCD'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cccd_image_back',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='CCCD Back'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cccd_image_front',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='CCCD Front'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
