# Generated by Django 3.2.6 on 2024-06-25 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0011_auto_20240528_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date', 'is_paid']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['room_number']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
