# Generated by Django 3.2.6 on 2024-10-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0012_auto_20240625_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
