# Generated by Django 3.2.6 on 2024-11-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0013_contract_is_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='is_expired',
        ),
        migrations.AddField(
            model_name='contract',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Currently effective'),
        ),
    ]
