# Generated by Django 3.2.6 on 2024-11-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0014_auto_20241127_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
