# Generated by Django 3.2.6 on 2025-07-11 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0015_alter_contract_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
            ],
        ),
        # migrations.AddField(
        #     model_name='room',
        #     name='house',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='department.house'),
        #     preserve_default=False,
        # ),
    ]
