# Generated by Django 3.2.6 on 2025-07-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0016_auto_20250711_1604'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='room',
        #     name='house',
        # ),
    ]
