# Generated by Django 3.2.6 on 2025-07-11 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0018_room_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='house',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.house'),
        ),
    ]
