# Generated by Django 3.2.6 on 2025-07-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0019_alter_room_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='house',
        ),
    ]
