# Generated by Django 3.2.6 on 2025-07-11 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0020_remove_room_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.house'),
        ),
    ]
